### ISSUE TITLE
how can i get datasets??

### ISSUE THREAD

**Issue by wonny2001** [AnirudhGP/DrowsyDriverDetection#2]
in eyesPreprocess.py,
there are errors

/home/rainman/anaconda3/bin/python /home/rainman/src_python/DrowsyDriverDetection/eyesPreprocess.py
Traceback (most recent call last):
  File "/home/rainman/src_python/DrowsyDriverDetection/eyesPreprocess.py", line 37, in <module>
    dataset_closed, labels_closed = generate_dataset_closed()
  File "/home/rainman/src_python/DrowsyDriverDetection/eyesPreprocess.py", line 27, in generate_dataset_closed
    for filename in os.listdir(dir):
FileNotFoundError: [Errno 2] No such file or directory: 'Dataset/closedLeftEyes'

i think i need to have datasets below, how??

dirs = ['Dataset/openLeftEyes', 'Dataset/openRightEyes']
dirs2 = ['Dataset/closedLeftEyes', 'Dataset/closedRightEyes']

**Comment by AnirudhGP** [comment]
Hi wonny2001. The dataset is available for download in the first link that is mentioned in the description : 
http://parnec.nuaa.edu.cn/xtan/data/ClosedEyeDatabases.html

I downloaded the 3rd dataset in that link which contains 24x24 eye images. 
Once you download them you will see the folders that are mentioned in the code. Save the folders in any directory (I called it 'Dataset') and put the path to that directory in the code. 

'dirs' and 'dirs2' should point to the folders containing the open eyes and closed eyes respectively.

Let me know if you need any more help.

Thanks

**Comment by wonny2001** [comment]
Thank you ^^
